version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
    nodejs: "20"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: app/requirements.txt
    - method: pip
      path: .

formats:
  - pdf
  - epub
